### ISSUE TITLE
issue when make package sbservertweek

### ISSUE THREAD

**Issue by KarmaGYZ** [DiOS-Analysis/DiOS#12] opened 2016-06-24 05:28 UTC
Making stage for tweak SBServerTweak…
dpkg-deb: warning: deprecated compression type 'lzma'; use xz instead
dpkg-deb: error: parsing file '/Users/username/Desktop/Pilot/SBServerTweak/.theos/_/DEBIAN/control' near line 10 package 'de.fau.cs.dios.pilot.sbservertweak:iphoneos-arm':
 junk after word in 'Priority' field

mac OS X 10.11

**Comment by KarmaGYZ** [comment] 2016-06-24 05:28
Package: de.fau.cs.dios.pilot.sbservertweak
Name: DiOS Controller
Depends: mobilesubstrate, cycript, apt, sudo
Architecture: iphoneos-arm
Description: DiOS Automator SpringBoard Tweak. Allows app installation and execution using a HTTP REST API.
Maintainer: Andreas Weinlein
Author: Andreas Weinlein
Section: Tweaks
Tag: role::hacker
Priority: standardVersion: 2.0.0-12+debug
Installed-Size: 1872

**Comment by awein** [comment] 2016-07-24 12:58
I'm unable to reproduce this issue.
Which version of theos are you using?
Have you tried <https://github.com/theos/theos>?

**Comment by L45eMy** [comment] 2016-08-04 06:19
This seems to be an issue with the `control` file in `layout/DEBIAN`. Theos is adding a version field and the `control` file seems to be missing a newline after the last line (at least when `cat layout/DEBIAN/control`ing it). This puts the Version field in the same line as the Priority field (`Priority: standardVersion: 2.0.0-2+debug`).

Use `echo >> layout/DEBIAN/control` to add the missing newline, verify it with `cat` and `make package` should run now.

**Comment by awein** [comment] 2016-08-04 08:44
Fixed with https://github.com/DiOS-Analysis/Pilot/commit/d710335cddd788e3c7f6c08b79cf734d298c1ce7

**Closed as completed by awein** 2016-08-04 08:44 UTC
